kind: ConfigMap
apiVersion: v1
metadata:
  name: apache-conf
  namespace: apache1
data:
  index.html: |
    <html>
    <body>
    <h1> Dette er dev apache hvis du leser dette så leser du informasjon fra dev /h1>
    </body>
    </html>
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
  namespace: apache1
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 1
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: apache-mount
          mountPath: /usr/local/apache2/htdocs/index.html
          subPath: index.html
      volumes:
      - name: apache-mount
        configMap:
          name: apache-conf
          items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: apache2
  namespace: apache1
  labels:
    app: apache
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30062
  selector:
    app: apache2
