apiVersion: v1
kind: Service
metadata:
  name: beetmanifest
  namespace: beetapache
spec:
  type: ClusterIP
  clusterIP: 10.103.173.59
  selector:
    app: beetroot
  ports:
      # By default and for convenience, the targetPort is set to the same value as the port field.
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)