apiVersion: apps/v1
kind: Deployment
metadata:
  name: beetroot-deployment
  namespace: beetapache
  labels:
    app: beetroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beetroot
  template:
    metadata:
      labels:
        app: beetroot
    spec:
      containers:
      - name: beetroot
        image: okayipullup/letsgo:latest
        ports:
        - containerPort: 8080