kind: ConfigMap
apiVersion: v1
metadata:
  name: apache-conf
  namespace: apache1
data:
  index.html: |
    <html>
    <body>
    <h1> Dette er prod aapache greia ok ok ok ok </h1>
    </body>
    </html>   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache1
  namespace: apache1
spec:
  selector:
    matchLabels:
      app: apache1
  replicas: 1
  template:
    metadata:
      labels:
        app: apache1
    spec:
      containers:
      - name: apache1
        image: httpd:latest
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: apache-mount
          mountPath: /usr/local/apache2/htdocs/index.html
          subPath: index.html
      volumes:
      - name: apache-mount
        configMap:
          name: apache-conf
          items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: apache1
  namespace: apache1
  labels:
    app: apache1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30055
  selector:
    app: apache1
