apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache1
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: apache-mount
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
      volumes:
      - name: apache-mount
        configMap:
          name: apache-conf
          items:
          - key: httpd.conf
            path: httpd.conf
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: apache1
  labels:
    app: apache
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30056
  selector:
    app: apache
